### ISSUE TITLE
Start issue

### ISSUE THREAD

**Issue by Scraayp** [Androz2091/Sworder-Dashboard.io#1]
Hey androz,
If you try to start the bot you will get a error: 
Error: TypeError: Cannot read property 'port' of undefined
\Sworder-Dashboard.io\app.js:19:19)

I can't find the issue right away in the code, maybe you can :)

**Comment by Androz2091** [comment]
Thank you, it's fixed by https://github.com/Androz2091/Sworder-Dashboard.io/commit/ddb00cbffeff5a1b8814190ee49b90122ef2f62e
